"""
Run once to populate the database with sample books.
  cd backend
  python seed_data.py
"""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from app.database import SessionLocal, engine
from app.models import Base, Book

Base.metadata.create_all(bind=engine)

BOOKS = [
    {
        "title": "The Night Circus",
        "author": "Erin Morgenstern",
        "genre": "Fantasy",
        "isbn": "9780385534635",
        "pages": 387,
        "year": 2011,
        "description": "A mysterious circus appears without warning, open only at night. Two young magicians, raised as fierce rivals by their guardians, discover they are pitted against each other in a contest whose rules they barely understand—and fall deeply in love.",
        "mood_tags": ["Dreamy", "Romantic", "Adventurous"],
        "moods": "Dreamy,Romantic,Adventurous",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385534635-L.jpg",
    },
    {
        "title": "Six of Crows",
        "author": "Leigh Bardugo",
        "genre": "Fantasy",
        "isbn": "9781627792127",
        "pages": 465,
        "year": 2015,
        "description": "Criminal prodigy Kaz Brekker assembles a crew of dangerous outcasts for a heist that could make them rich beyond their wildest dreams—if they survive.",
        "mood_tags": ["Adventurous", "Thrilling", "Motivated"],
        "moods": "Adventurous,Thrilling,Motivated",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781627792127-L.jpg",
    },
    {
        "title": "The Invisible Life of Addie LaRue",
        "author": "V.E. Schwab",
        "genre": "Fantasy",
        "isbn": "9780765387561",
        "pages": 448,
        "year": 2020,
        "description": "A woman makes a Faustian bargain to live forever but is cursed to be forgotten by everyone she meets—until, 300 years later, she meets a man who remembers her name.",
        "mood_tags": ["Dreamy", "Sad", "Romantic"],
        "moods": "Dreamy,Sad,Romantic",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780765387561-L.jpg",
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "genre": "Science Fiction",
        "isbn": "9780593135204",
        "pages": 476,
        "year": 2021,
        "description": "A lone astronaut wakes up with no memory millions of miles from home—the only person who can save Earth from an extinction-level threat.",
        "mood_tags": ["Motivated", "Adventurous", "Happy"],
        "moods": "Motivated,Adventurous,Happy",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    },
    {
        "title": "The Song of Achilles",
        "author": "Madeline Miller",
        "genre": "Historical Fiction",
        "isbn": "9780062060624",
        "pages": 378,
        "year": 2012,
        "description": "A retelling of the Iliad through the eyes of Patroclus—his friendship, devotion, and love for the brilliant and golden Achilles, and their shared doom.",
        "mood_tags": ["Romantic", "Sad", "Dreamy"],
        "moods": "Romantic,Sad,Dreamy",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062060624-L.jpg",
    },
    {
        "title": "Piranesi",
        "author": "Susanna Clarke",
        "genre": "Fantasy",
        "isbn": "9781635575637",
        "pages": 272,
        "year": 2020,
        "description": "A man lives in a House of infinite halls, endless statues, and tidal seas—and begins to suspect he is not as alone as he believes.",
        "mood_tags": ["Dreamy", "Mystery", "Peaceful"],
        "moods": "Dreamy,Mystery,Peaceful",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781635575637-L.jpg",
    },
    {
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "genre": "Fantasy",
        "isbn": "9780756404741",
        "pages": 662,
        "year": 2007,
        "description": "The riveting first-person narrative of Kvothe—a legendary figure who grew from street urchin to wizard, assassin, and bard.",
        "mood_tags": ["Adventurous", "Dreamy", "Motivated"],
        "moods": "Adventurous,Dreamy,Motivated",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
    },
    {
        "title": "Anxious People",
        "author": "Fredrik Backman",
        "genre": "Contemporary Fiction",
        "isbn": "9781501160769",
        "pages": 352,
        "year": 2020,
        "description": "An inept bank robber accidentally takes a group of strangers hostage at an apartment viewing—leading to unexpected connections and profound humanity.",
        "mood_tags": ["Happy", "Peaceful", "Sad"],
        "moods": "Happy,Peaceful,Sad",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781501160769-L.jpg",
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "genre": "Literary Fiction",
        "isbn": "9780062315007",
        "pages": 208,
        "year": 1988,
        "description": "A shepherd boy journeys from Spain to Egypt in search of treasure and discovers that the greatest treasure lies within.",
        "mood_tags": ["Motivated", "Peaceful", "Dreamy"],
        "moods": "Motivated,Peaceful,Dreamy",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    },
    {
        "title": "Norwegian Wood",
        "author": "Haruki Murakami",
        "genre": "Literary Fiction",
        "isbn": "9780375704024",
        "pages": 296,
        "year": 1987,
        "description": "A melancholy coming-of-age story set in 1960s Tokyo about a young man who falls for two women—one grounded in reality, one lost in grief.",
        "mood_tags": ["Sad", "Heartbroken", "Peaceful"],
        "moods": "Sad,Heartbroken,Peaceful",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780375704024-L.jpg",
    },
    {
        "title": "Rebecca",
        "author": "Daphne du Maurier",
        "genre": "Gothic Mystery",
        "isbn": "9780380730407",
        "pages": 380,
        "year": 1938,
        "description": "A young bride arrives at the brooding Manderley estate and finds herself haunted by the memory of her husband's first wife.",
        "mood_tags": ["Thrilling", "Mystery", "Dreamy"],
        "moods": "Thrilling,Mystery,Dreamy",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780380730407-L.jpg",
    },
    {
        "title": "Good Omens",
        "author": "Terry Pratchett & Neil Gaiman",
        "genre": "Comedy Fantasy",
        "isbn": "9780060853976",
        "pages": 383,
        "year": 1990,
        "description": "An angel and a demon who have grown fond of Earth reluctantly team up to prevent the Apocalypse.",
        "mood_tags": ["Happy", "Adventurous", "Peaceful"],
        "moods": "Happy,Adventurous,Peaceful",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780060853976-L.jpg",
    },
    {
        "title": "The House in the Cerulean Sea",
        "author": "TJ Klune",
        "genre": "Fantasy",
        "isbn": "9781250217288",
        "pages": 394,
        "year": 2020,
        "description": "A magical social worker is sent to an orphanage of dangerous children and finds his quiet life upended by found family and unexpected love.",
        "mood_tags": ["Peaceful", "Happy", "Romantic"],
        "moods": "Peaceful,Happy,Romantic",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781250217288-L.jpg",
    },
    {
        "title": "Circe",
        "author": "Madeline Miller",
        "genre": "Mythology",
        "isbn": "9780316556347",
        "pages": 393,
        "year": 2018,
        "description": "The daughter of Helios discovers her power to transform her enemies into monsters, pitting her against gods, heroes, and her own nature.",
        "mood_tags": ["Adventurous", "Dreamy", "Motivated"],
        "moods": "Adventurous,Dreamy,Motivated",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg",
    },
    {
        "title": "Mexican Gothic",
        "author": "Silvia Moreno-Garcia",
        "genre": "Horror Mystery",
        "isbn": "9780525620785",
        "pages": 320,
        "year": 2020,
        "description": "A glamorous socialite investigates a crumbling mansion in 1950s Mexico and uncovers something far darker than the family secrets she was hired to find.",
        "mood_tags": ["Thrilling", "Mystery", "Dreamy"],
        "moods": "Thrilling,Mystery,Dreamy",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780525620785-L.jpg",
    },
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "genre": "Contemporary Fiction",
        "isbn": "9780525559474",
        "pages": 304,
        "year": 2020,
        "description": "Between life and death lies a library where every book represents a different life you could have lived—and the chance to undo your regrets.",
        "mood_tags": ["Sad", "Peaceful", "Motivated"],
        "moods": "Sad,Peaceful,Motivated",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    },
    {
        "title": "Daisy Jones & The Six",
        "author": "Taylor Jenkins Reid",
        "genre": "Contemporary Fiction",
        "isbn": "9781524798628",
        "pages": 368,
        "year": 2019,
        "description": "A fictional oral history of a 1970s rock band at the height of their fame—and the electric, destructive relationship at its core.",
        "mood_tags": ["Romantic", "Heartbroken", "Adventurous"],
        "moods": "Romantic,Heartbroken,Adventurous",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781524798628-L.jpg",
    },
    {
        "title": "The Seven Husbands of Evelyn Hugo",
        "author": "Taylor Jenkins Reid",
        "genre": "Historical Fiction",
        "isbn": "9781250122185",
        "pages": 400,
        "year": 2017,
        "description": "A reclusive Hollywood icon finally grants an exclusive interview—and the story of her seven marriages reveals a love story she kept hidden for decades.",
        "mood_tags": ["Romantic", "Dreamy", "Heartbroken"],
        "moods": "Romantic,Dreamy,Heartbroken",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781250122185-L.jpg",
    },
    {
        "title": "Dune",
        "author": "Frank Herbert",
        "genre": "Science Fiction",
        "isbn": "9780441013593",
        "pages": 688,
        "year": 1965,
        "description": "On the desert planet Arrakis, a noble family's heir must survive betrayal, navigate politics, and become the messianic leader of a people.",
        "mood_tags": ["Adventurous", "Motivated", "Thrilling"],
        "moods": "Adventurous,Motivated,Thrilling",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
    },
    {
        "title": "The Hitchhiker's Guide to the Galaxy",
        "author": "Douglas Adams",
        "genre": "Comedy Science Fiction",
        "isbn": "9780345391803",
        "pages": 224,
        "year": 1979,
        "description": "Moments before Earth is demolished for a hyperspace bypass, Arthur Dent is whisked into space—and discovers the universe is even odder than he imagined.",
        "mood_tags": ["Happy", "Adventurous", "Peaceful"],
        "moods": "Happy,Adventurous,Peaceful",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
    },
    {
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "genre": "Dystopian Fiction",
        "isbn": "9780385490818",
        "pages": 311,
        "year": 1985,
        "description": "In the theocratic dictatorship of Gilead, a woman reduced to her reproductive function fights to survive and resist.",
        "mood_tags": ["Thrilling", "Sad", "Motivated"],
        "moods": "Thrilling,Sad,Motivated",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
    },
    {
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "genre": "Mystery",
        "isbn": "9780735224292",
        "pages": 368,
        "year": 2018,
        "description": "An abandoned girl raises herself in the North Carolina marshes—and becomes the prime suspect in a murder that shakes her small town.",
        "mood_tags": ["Peaceful", "Sad", "Mystery"],
        "moods": "Peaceful,Sad,Mystery",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780735224292-L.jpg",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "genre": "Memoir",
        "isbn": "9780399590504",
        "pages": 334,
        "year": 2018,
        "description": "A woman raised by survivalists in rural Idaho keeps herself out of school until she is seventeen—then bootstraps her way to a PhD at Cambridge.",
        "mood_tags": ["Motivated", "Sad", "Adventurous"],
        "moods": "Motivated,Sad,Adventurous",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    },
    {
        "title": "A Gentleman in Moscow",
        "author": "Amor Towles",
        "genre": "Historical Fiction",
        "isbn": "9780670026190",
        "pages": 462,
        "year": 2016,
        "description": "A count sentenced to house arrest in a Moscow luxury hotel in 1922 finds that a life without ambition can still be a life of purpose, pleasure, and depth.",
        "mood_tags": ["Peaceful", "Happy", "Dreamy"],
        "moods": "Peaceful,Happy,Dreamy",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780670026190-L.jpg",
    },
    {
        "title": "Kafka on the Shore",
        "author": "Haruki Murakami",
        "genre": "Magical Realism",
        "isbn": "9781400079278",
        "pages": 480,
        "year": 2002,
        "description": "A teenage runaway and an old man who talks to cats are pulled towards each other across Japan in a labyrinthine story of fate, memory, and the unconscious.",
        "mood_tags": ["Dreamy", "Mystery", "Sad"],
        "moods": "Dreamy,Mystery,Sad",
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781400079278-L.jpg",
    },
]


def seed():
    db = SessionLocal()
    try:
        existing = db.query(Book).count()
        if existing > 0:
            print(f"Database already has {existing} books. Skipping seed.")
            return
        for data in BOOKS:
            book = Book(**data)
            db.add(book)
        db.commit()
        print(f"✅  Seeded {len(BOOKS)} books into the database.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
